function onButtonDown(obj)
%onButtonDown  Begin a middle-drag (or Shift+Left) pan gesture.
%   Snapshots the starting pointer pixel and viewport once per drag (not on
%   every motion event) so onButtonMotion can translate pixel deltas into
%   time (and, in traces mode, amplitude) or channel-window panning.

if ~obj.ActiveFcn(); return; end
if ~obj.cursorOverAxes(); return; end
if isempty(obj.Figure) || ~isvalid(obj.Figure) || ~strcmp(obj.Figure.SelectionType, 'extend')
    return
end

obj.Pan = struct( ...
    'active',   true, ...
    'startPix', obj.Figure.CurrentPoint, ...
    'axPix',    getpixelposition(obj.Axes, true), ...
    'tLeft0',   obj.TimeWindowStart, ...
    'yOff0',    obj.YOffset, ...
    'firstCh0', obj.FirstVisibleChannel, ...
    'chanMode', obj.NumVisibleChannels < obj.NumChannels);
obj.Figure.WindowButtonMotionFcn = @(~, ~) obj.onButtonMotion();
end
