function buildUI(obj)
    %BUILDUI Lay out the controls beside the plot.

    obj.Fig = uifigure(Name = "ECM Browser", Position = [80 80 1280 780]);

    obj.buildMenus();

    layout = uigridlayout(obj.Fig, [1 2]);
    layout.ColumnWidth = {270, '1x'};
    layout.RowHeight = {'1x'};

    controls = uipanel(layout, Title = "Display");

    % The plot, with the toolbar above it. The two share a column of
    % their own so that REFRESH can empty the plot panel without
    % taking the buttons over it down with the plot.
    plotColumn = uigridlayout(layout, [2 1]);
    plotColumn.ColumnWidth = {'1x'};
    plotColumn.RowHeight = {26, '1x'};
    plotColumn.RowSpacing = 4;
    plotColumn.Padding = [0 0 0 0];

    obj.buildToolbar(plotColumn);
    obj.PlotPanel = uipanel(plotColumn, BorderType = "none");

    depth = obj.Data.grid.depth;

    grid = uigridlayout(controls, [29 2]);
    grid.ColumnWidth = {90, '1x'};
    % Every row is a fixed height, the filter values list included: a
    % '1x' row in a scrollable grid is squeezed to nothing as soon as
    % the fixed rows add up to more than the panel can show, which is
    % how that list came to be laid out but never drawn.
    grid.RowHeight = [repmat({24}, 1, 8), {110}, repmat({24}, 1, 4), ...
        {240}, {24}, {140}, ...
        repmat({24}, 1, 9), repmat({24}, 1, 3), {40}];
    grid.RowSpacing = 6;

    % The rows below Tile by add up to more than a window of ordinary
    % height can show, so the panel scrolls rather than dropping Config
    % and the status line off the bottom of itself.
    grid.Scrollable = "on";

    obj.SignalDropDown = obj.addRow(grid, "Signal", ...
        @() uidropdown(grid, Items = ["smoothed", "raw"]));

    obj.NormalizeDropDown = obj.addRow(grid, "Normalize", ...
        @() uidropdown(grid, Items = obj.NormalizeModes, ...
            Tooltip = "Rescale the intensities before they are drawn."));

    obj.ScopeDropDown = obj.addRow(grid, "Scope", ...
        @() uidropdown(grid, Items = obj.NormalizeScopes, ...
            Tooltip = "How many sections share one scale."));

    obj.RefMinField = obj.addRow(grid, "Ref. min", ...
        @() uieditfield(grid, "numeric", Value = floor(min(depth)), ...
            Tooltip = "Start of the depth window the normalization is taken from."));

    obj.RefMaxField = obj.addRow(grid, "Ref. max", ...
        @() uieditfield(grid, "numeric", Value = ceil(max(depth)), ...
            Tooltip = "End of that window, and of the band the baseline modes measure."));

    obj.CompareDropDown = obj.addRow(grid, "Compare", ...
        @() uidropdown(grid, Items = obj.CompareOps, ...
            Tooltip = "Measure one value of a field against another " + ...
                "within the same subject, plate, or whatever else " + ...
                "is matched on below, and draw the comparison in " + ...
                "place of the sections behind it. a is the value " + ...
                "compared and b the reference: difference is a - b, " + ...
                "ratio a / b, log2 ratio log2(a / b), % change " + ...
                "100 (a - b) / b, and normalized difference " + ...
                "(a - b) / (a + b)."));

    obj.CompareFieldDropDown = obj.addRow(grid, "Compare by", ...
        @() uidropdown(grid, Items = [obj.NoField; obj.GroupFields], ...
            Tooltip = "The field whose values are measured against " + ...
                "each other."), ...
        @(~,~) obj.onCompareFieldChanged());

    obj.CompareRefDropDown = obj.addRow(grid, "Reference", ...
        @() uidropdown(grid, Items = cellstr(obj.NoField), ...
            Tooltip = "Which value of that field is b, the one the " + ...
                "others are measured against. A field whose values " + ...
                "are peers -- subject, say -- has no such value and " + ...
                "is compared within itself instead: each value " + ...
                "against every section of the match holding another, " + ...
                "or each two values against each other in turn."));

    obj.PairListBox = obj.addRow(grid, "Pair within", ...
        @() uilistbox(grid, Items = [obj.NoField; obj.FilterFields], ...
            Multiselect = "on", ...
            Tooltip = "Which fields two sections have to agree on " + ...
                "to be compared -- subject and plate, usually. " + ...
                "Sections that match on all of them are averaged " + ...
                "per side first, then the two sides compared."));

    obj.ShowDropDown = obj.addRow(grid, "Show", ...
        @() uidropdown(grid, Items = ["sections", "group mean", "peak summary"]));

    obj.ErrorDropDown = obj.addRow(grid, "Error band", ...
        @() uidropdown(grid, Items = obj.ErrorBands, ...
            Tooltip = "What the shading around a group mean measures. " + ...
                "The bootstrap interval makes no assumption about the " + ...
                "shape of the sections' spread and needs the " + ...
                "Statistics and Machine Learning Toolbox."));

    obj.SectionsCheckBox = uicheckbox(grid, ...
        Text = "Sections behind the mean", ...
        Value = true, ...
        ValueChangedFcn = @(~,~) obj.refresh());
    obj.SectionsCheckBox.Layout.Column = [1 2];

    obj.GroupDropDown = obj.addRow(grid, "Color by", ...
        @() uidropdown(grid, Items = [obj.NoField; obj.GroupFields]));

    obj.TileListBox = obj.addRow(grid, "Tile by", ...
        @() uilistbox(grid, Items = [obj.NoField; obj.GroupFields], ...
            Multiselect = "on", ...
            Tooltip = "Pick several to split on every combination of them: " + ...
                "the last runs across the columns, the rest down the rows."));

    obj.FilterFieldDropDown = obj.addRow(grid, "Filter by", ...
        @() uidropdown(grid, Items = [obj.AllSections; obj.FilterFields]), ...
        @(~,~) obj.onFilterFieldChanged());

    obj.FilterValuesListBox = uilistbox(grid, ...
        Items = {}, ...
        Multiselect = "on", ...
        Tooltip = "Which of the filter field's values to keep. " + ...
            "Empty until a field is picked above.", ...
        ValueChangedFcn = @(~,~) obj.refresh());
    obj.FilterValuesListBox.Layout.Column = [1 2];

    obj.DepthMinField = obj.addRow(grid, "Depth min", ...
        @() uieditfield(grid, "numeric", Value = floor(min(depth))));

    obj.DepthMaxField = obj.addRow(grid, "Depth max", ...
        @() uieditfield(grid, "numeric", Value = ceil(max(depth))));

    obj.LegendDropDown = obj.addRow(grid, "Legend", ...
        @() uidropdown(grid, Items = obj.LegendPlacements, ...
            Tooltip = "One legend per plot, or one for the whole " + ...
                "figure placed outside the plots."));

    obj.SpacingDropDown = obj.addRow(grid, "Tile spacing", ...
        @() uidropdown(grid, Items = obj.TileSpacings, ...
            Tooltip = "How much room is left between one tile and the next."));

    obj.PaddingDropDown = obj.addRow(grid, "Padding", ...
        @() uidropdown(grid, Items = obj.LayoutPaddings, ...
            Tooltip = "How much room is left around the grid as a whole."));

    obj.TickLabelDropDown = obj.addRow(grid, "Tick labels", ...
        @() uidropdown(grid, Items = obj.TickLabelModes, ...
            Tooltip = "Which tiles carry the numbers on their axes. " + ...
                "Reading a tile in the middle off the edges of the " + ...
                "grid only holds while the axes are linked."));

    obj.LinkCheckBox = uicheckbox(grid, Text = "Link axes", Value = true, ...
        ValueChangedFcn = @(~,~) obj.refresh());
    obj.LinkCheckBox.Layout.Column = [1 2];

    obj.TransposeCheckBox = uicheckbox(grid, ...
        Text = "Transpose axes", ...
        Value = false, ...
        Tooltip = "Lay the axes out the other way round: the field " + ...
            "that ran across the columns runs down the rows.", ...
        ValueChangedFcn = @(~,~) obj.refresh());
    obj.TransposeCheckBox.Layout.Column = [1 2];

    obj.AxisQuantityCheckBox = uicheckbox(grid, ...
        Text = "Label depth/intensity too", ...
        Value = false, ...
        Tooltip = "The layout's axis labels name the Tile by " + ...
            "field(s) split across the grid. Check this to also " + ...
            "name the depth and intensity every tile plots, which " + ...
            "is otherwise left off as understood.", ...
        ValueChangedFcn = @(~,~) obj.refresh());
    obj.AxisQuantityCheckBox.Layout.Column = [1 2];

    obj.ConfigDropDown = uidropdown(grid, Items = cellstr(obj.NoConfig), ...
        Tooltip = "Every control on this panel, saved under an " + ...
            "autogenerated name and kept from one session to the next.", ...
        ValueChangedFcn = @(~,~) obj.onConfigSelected());
    obj.ConfigDropDown.Layout.Column = [1 2];

    uibutton(grid, Text = "Save", ...
        Tooltip = "Save the panel as it is now under a new name.", ...
        ButtonPushedFcn = @(~,~) obj.onSaveConfig());
    uibutton(grid, Text = "Delete", ...
        Tooltip = "Remove the configuration named above.", ...
        ButtonPushedFcn = @(~,~) obj.onDeleteConfig());

    purgeButton = uibutton(grid, Text = "Purge all saved configs", ...
        ButtonPushedFcn = @(~,~) obj.onPurgeConfigs());
    purgeButton.Layout.Column = [1 2];

    obj.StatusLabel = uilabel(grid, Text = "", WordWrap = "on", ...
        VerticalAlignment = "top");
    obj.StatusLabel.Layout.Column = [1 2];

    obj.applyDefaults();
    obj.refreshConfigList();

end
