        function buildConfigureTab(obj)
            uilabel(obj.TabConfigure, "Position", [20 690 220 22], "Text", "Grouping Variables");
            obj.GroupVarsList = uilistbox(obj.TabConfigure, ...
                "Position", [20 520 320 170], ...
                "Multiselect", "on");

            uilabel(obj.TabConfigure, "Position", [380 690 120 22], "Text", "Peak Range Min");
            obj.PeakMinField = uieditfield(obj.TabConfigure, "numeric", ...
                "Position", [380 664 120 24], "Value", 0);

            uilabel(obj.TabConfigure, "Position", [520 690 120 22], "Text", "Peak Range Max");
            obj.PeakMaxField = uieditfield(obj.TabConfigure, "numeric", ...
                "Position", [520 664 120 24], "Value", 300);

            uilabel(obj.TabConfigure, "Position", [380 630 120 22], "Text", "Smoothing");
            obj.SmoothMethodDropDown = uidropdown(obj.TabConfigure, ...
                "Position", [380 604 160 24], ...
                "Items", {'gaussian', 'movmean', 'movmedian', 'sgolay'}, ...
                "Value", 'gaussian');

            uilabel(obj.TabConfigure, "Position", [560 630 120 22], "Text", "Smooth Window");
            obj.SmoothWindowField = uieditfield(obj.TabConfigure, "numeric", ...
                "Position", [560 604 120 24], "Value", 50, ...
                "LowerLimit", 1);

            uilabel(obj.TabConfigure, "Position", [700 630 120 22], "Text", "Error Metric");
            obj.ErrorMetricDropDown = uidropdown(obj.TabConfigure, ...
                "Position", [700 604 120 24], ...
                "Items", {'sem', 'std', 'ci95'}, ...
                "Value", 'sem');

            uilabel(obj.TabConfigure, "Position", [840 630 120 22], "Text", "Normalization");
            obj.NormalizeDropDown = uidropdown(obj.TabConfigure, ...
                "Position", [840 604 120 24], ...
                "Items", {'none', 'zscore', 'minmax'}, ...
                "Value", 'none');

            obj.RecomputeButton = uibutton(obj.TabConfigure, "push", ...
                "Position", [980 602 160 28], ...
                "Text", "Recompute", ...
                "ButtonPushedFcn", @(~,~) obj.onRecompute());
        end
