        function buildPlotTab(obj)
            % Create left control panel
            controlPanel = uipanel(obj.TabPlot, ...
                "Position", [10 10 280 720], ...
                "Title", "Plot Controls", ...
                "FontWeight", "bold");

            % Plot Type
            uilabel(controlPanel, "Position", [10 680 150 22], "Text", "Plot Type");
            obj.PlotTypeDropDown = uidropdown(controlPanel, ...
                "Position", [10 654 260 24], ...
                "Items", {'Raw + Smoothed Overlay', 'Grouped Mean +/- Error', 'Peak Summary', 'Heatmap', 'Per-Subject Facets'}, ...
                "Value", 'Raw + Smoothed Overlay', ...
                "ValueChangedFcn", @(~,~) obj.onRenderPlot());

            % Plot Colors
            uilabel(controlPanel, "Position", [10 628 150 22], "Text", "Colors");
            obj.PlotColorDropDown = uidropdown(controlPanel, ...
                "Position", [10 604 260 24], ...
                "Items", {'lines', 'parula', 'turbo', 'gray', 'hot', 'cool', 'viridis', 'plasma', 'magma', 'inferno'}, ...
                "Value", 'lines', ...
                "ValueChangedFcn", @(~,~) obj.onRenderPlot());

            % Line width
            uilabel(controlPanel, "Position", [10 578 150 22], "Text", "Line Width");
            obj.PlotLineWidthField = uieditfield(controlPanel, 'numeric', ...
                "Position", [10 554 260 24], ...
                "Value", 1.5, ...
                "Limits", [0.25 10], ...
                "ValueChangedFcn", @(~,~) obj.onRenderPlot());

            % Separator
            uilabel(controlPanel, "Position", [10 520 260 2], "Text", "", "BackgroundColor", [0.7 0.7 0.7]);

            % Facet Variables Section
            uilabel(controlPanel, "Position", [10 500 260 22], "Text", "Facet Variables", "FontWeight", "bold");
            obj.FacetVarsList = uilistbox(controlPanel, ...
                "Position", [10 300 260 200], ...
                "Items", {}, ...
                "Value", {}, ...
                "Multiselect", "on");

            % Facet Layout Options
            uilabel(controlPanel, "Position", [10 280 260 22], "Text", "Facet Layout", "FontWeight", "bold");

            uilabel(controlPanel, "Position", [10 255 80 22], "Text", "Style");
            obj.FacetLayoutDropDown = uidropdown(controlPanel, ...
                "Position", [10 229 260 24], ...
                "Items", {'flow', 'horizontal', 'vertical', 'grid'}, ...
                "Value", 'flow');

            uilabel(controlPanel, "Position", [10 205 80 22], "Text", "Max Rows");
            obj.FacetMaxRowsField = uieditfield(controlPanel, 'numeric', ...
                "Position", [10 179 260 24], ...
                "Value", 2, ...
                "Limits", [1 20]);

            uilabel(controlPanel, "Position", [10 155 80 22], "Text", "Max Cols");
            obj.FacetMaxColsField = uieditfield(controlPanel, 'numeric', ...
                "Position", [10 129 260 24], ...
                "Value", 3, ...
                "Limits", [1 20]);

            uilabel(controlPanel, "Position", [10 105 260 22], "Text", "Facet Target", "FontWeight", "bold");
            obj.PlotInFigureButton = uibutton(controlPanel, "push", ...
                "Position", [10 79 126 24], ...
                "Text", "New Figure", ...
                "ButtonPushedFcn", @(~,~) obj.onRenderTiledFacets(false));
            obj.PlotInPanelButton = uibutton(controlPanel, "push", ...
                "Position", [144 79 126 24], ...
                "Text", "Inside Panel", ...
                "ButtonPushedFcn", @(~,~) obj.onRenderTiledFacets(true));

            % Main Plot Area (right side)
            obj.PlotAxes = uiaxes(obj.TabPlot, "Position", [300 10 950 720]);
            title(obj.PlotAxes, "Plot Output")
            xlabel(obj.PlotAxes, "Distance")
            ylabel(obj.PlotAxes, "Intensity")
            grid(obj.PlotAxes, "on")

            % Inline facet panel (same footprint as PlotAxes, hidden by default)
            obj.FacetPanel = uipanel(obj.TabPlot, ...
                "Position", [300 10 950 720], ...
                "BorderType", "none", ...
                "Visible", "off");
        end
