        function buildExportTab(obj)
            obj.ExportProcessedButton = uibutton(obj.TabExport, "push", ...
                "Position", [20 680 220 34], ...
                "Text", "Export Processed CSV", ...
                "ButtonPushedFcn", @(~,~) obj.onExportProcessed());

            obj.ExportSummaryButton = uibutton(obj.TabExport, "push", ...
                "Position", [260 680 220 34], ...
                "Text", "Export Summary CSV", ...
                "ButtonPushedFcn", @(~,~) obj.onExportSummary());

            obj.ExportPngButton = uibutton(obj.TabExport, "push", ...
                "Position", [500 680 180 34], ...
                "Text", "Export Figure PNG", ...
                "ButtonPushedFcn", @(~,~) obj.onExportPng());

            obj.ExportFigButton = uibutton(obj.TabExport, "push", ...
                "Position", [700 680 180 34], ...
                "Text", "Export Figure FIG", ...
                "ButtonPushedFcn", @(~,~) obj.onExportFig());

            obj.ExportScriptButton = uibutton(obj.TabExport, "push", ...
                "Position", [900 680 220 34], ...
                "Text", "Export Repro Script", ...
                "ButtonPushedFcn", @(~,~) obj.onExportScript());

            obj.SaveSessionButton = uibutton(obj.TabExport, "push", ...
                "Position", [20 634 220 34], ...
                "Text", "Save MAT Session", ...
                "ButtonPushedFcn", @(~,~) obj.onSaveSession());

            obj.LoadSessionButton = uibutton(obj.TabExport, "push", ...
                "Position", [260 634 220 34], ...
                "Text", "Load MAT Session", ...
                "ButtonPushedFcn", @(~,~) obj.onLoadSession());
        end
