        function buildLoadTab(obj)
            uilabel(obj.TabLoad, "Position", [20 690 120 22], "Text", "Root Folder");
            obj.RootPathField = uieditfield(obj.TabLoad, "text", "Position", [20 664 930 24], "Value", pwd);
            uibutton(obj.TabLoad, "push", "Position", [960 664 120 24], "Text", "Browse", ...
                "ButtonPushedFcn", @(~,~) obj.onBrowseRoot());

            uilabel(obj.TabLoad, "Position", [20 630 180 22], "Text", "Metadata CSV (optional)");
            obj.MetadataPathField = uieditfield(obj.TabLoad, "text", "Position", [20 604 930 24], "Value", "");
            uibutton(obj.TabLoad, "push", "Position", [960 604 120 24], "Text", "Browse", ...
                "ButtonPushedFcn", @(~,~) obj.onBrowseMetadata());

            obj.LoadButton = uibutton(obj.TabLoad, "push", "Position", [1100 634 140 44], "Text", "Load Data", ...
                "ButtonPushedFcn", @(~,~) obj.onLoadData());

            obj.LoadStatusLabel = uilabel(obj.TabLoad, "Position", [20 566 1200 24], "Text", "Idle");

            obj.ValidationStatusLabel = uilabel(obj.TabLoad, "Position", [20 542 1200 22], "Text", "Validation: not run");
            obj.DiagnosticsStatusLabel = uilabel(obj.TabLoad, "Position", [20 518 900 22], "Text", "Diagnostics: none");
            obj.ExportDiagnosticsButton = uibutton(obj.TabLoad, "push", ...
                "Position", [960 514 160 28], ...
                "Text", "Export Diagnostics", ...
                "ButtonPushedFcn", @(~,~) obj.onExportDiagnostics());

            obj.DiagnosticsTable = uitable(obj.TabLoad, ...
                "Position", [20 20 1240 486], ...
                "Data", table(), ...
                "ColumnSortable", true, ...
                "RowName", []);
        end
