        function onExportScript(obj)
            [f, p] = uiputfile("*.m", "Save reproducible script as");
            if isequal(f, 0)
                return
            end

            fp = fullfile(p, f);
            fid = fopen(fp, "w");
            if fid < 0
                uialert(obj.Fig, "Could not open script file for writing.", "Export Error");
                return
            end

            c = onCleanup(@() fclose(fid));

            groupVarStr = join("'" + string(obj.GroupVarsList.Value) + "'", ", ");

            fprintf(fid, "%% Reproducible ECM analysis script generated by ECMAnalysisApp\n");
            fprintf(fid, "%% Generated: %s\n\n", datestr(now));
            fprintf(fid, "rootPath = '%s';\n", string(obj.RootPathField.Value));
            fprintf(fid, "metadataCSV = '%s';\n\n", string(obj.MetadataPathField.Value));
            fprintf(fid, "S = combine_values_csv(rootPath, ...\n");
            if strtrim(string(obj.MetadataPathField.Value)) ~= ""
                fprintf(fid, "    metadataCSV = metadataCSV, ...\n");
            end
            fprintf(fid, "    continueOnError = true);\n\n");
            fprintf(fid, "A = ecm_prepare_analysis_data(S, ...\n");
            fprintf(fid, "    groupVars = [%s], ...\n", groupVarStr);
            fprintf(fid, "    peakRange = [%g %g], ...\n", obj.PeakMinField.Value, obj.PeakMaxField.Value);
            fprintf(fid, "    smoothingMethod = '%s', ...\n", obj.SmoothMethodDropDown.Value);
            fprintf(fid, "    smoothingWindow = %g, ...\n", obj.SmoothWindowField.Value);
            fprintf(fid, "    errorMetric = '%s', ...\n", obj.ErrorMetricDropDown.Value);
            fprintf(fid, "    normalizeMode = '%s');\n", obj.NormalizeDropDown.Value);

            clear c
        end
