function h = xyline(ax)
if nargin == 0 || isempty(ax), ax = gca; end
h = line(ax,[-1e9 1e9],[-1e9 1e9], ...
    Color = 'k', ...
    AffectAutoLimits = "off", ...
    HandleVisibility = "off");
if nargin == 0, clear h; end